name:                mset
version:             0.1.0.0
github:              "runarorama/mset"
license:             BSD3
author:              "Rúnar Bjarnason"
maintainer:          "runar@bjarnason.is"
copyright:           "2018 Rúnar Bjarnason"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on Github at <https://github.com/runarorama/mset#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- groups

library:
  source-dirs: src

tests:
  mset-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mset
